# Use Node.js base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy and install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY index.template.html .
COPY server.js .

# Expose port
EXPOSE 3000

# Start the server
CMD ["node", "server.js"]
